default: &default
  adapter: postgresql
  encoding: unicode
  host: db-postgres
  port: 5432
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: nex

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
