version: "3"

volumes:
  node_modules:

services:
  db:
    container_name: db-postgres
    image: postgres:15.4-bullseye
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: nex
    healthcheck:
      test: pg_isready -U ${DB_USER} -d nex
      interval: 2s
      timeout: 3s
      retries: 40

  backend:
    build: ./backend
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db/development

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
