version: "3"

volumes:
  node_modules:

services:
  db:
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  backend:
    build: ./backend
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db/development

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
