databases:
  - name: Nex_DB
    databaseName: nex_db
    user: nex_db_user
    region: singapore

services:
  - type: web
    name: nex_db_user
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Nex_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
